// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	UserID    int32
	Token     string
	CreatedAt pgtype.Timestamp
	ExpiredAt pgtype.Timestamp
}

type Token struct {
	Token     pgtype.Text
	ExpiredAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
